[tool.poetry]
name = "poetry-example"
version = "1.0.2"
description = "Example of project managed via Poetry"
authors = ["Rafael Laboissière <rafael@laboissiere.net>"]
license = "GLP-3+"
readme = "README.md"
packages = [
    { include = "poetryex" },
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.autopub]
project-name = "Poetry Example"
git-username = "rlaboiss"
git-email = "rafael@laboissiere.net"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
